### ISSUE TITLE
App crashes when trying to reorder downloads.

### ISSUE THREAD

**Issue by THElegend5** [tachiyomiorg/tachiyomi#6400]
### Steps to reproduce

1. Download from two different sources .
2. Now try to reorder one of the sources over the other.

### Expected behavior

Downloads get reordered.

### Actual behavior

App crashes.

### Crash logs

--------- beginning of system
--------- beginning of crash
12-28 13:24:34.838  7542  7542 E AndroidRuntime: FATAL EXCEPTION: main
12-28 13:24:34.838  7542  7542 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 7542
12-28 13:24:34.838  7542  7542 E AndroidRuntime: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
12-28 13:24:34.838  7542  7542 E AndroidRuntime:  ViewHolder 1:DownloadHeaderHolder{97ae2dd position=2 id=1333211599, oldPos=-1, pLpos:-1 not recyclable(1)} 
12-28 13:24:34.838  7542  7542 E AndroidRuntime:  View Holder 2:DownloadHeaderHolder{42f2a83 position=0 id=1333211599, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{18c6a7e VFED..... ......ID 0,0-1080,2298 #7f09024b app:id/recycler}, adapter:eu.kanade.tachiyomi.ui.download.DownloadAdapter@cafebdf, layout:androidx.recyclerview.widget.LinearLayoutManager@e3f902c, context:eu.kanade.tachiyomi.ui.main.MainActivity@3f63329
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:62)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:23)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:6)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:809)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:985)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
12-28 13:24:34.838  7542  7542 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: FATAL EXCEPTION: main
12-28 13:24:51.153 16147 16147 E AndroidRuntime: Process: eu.kanade.tachiyomi.debug, PID: 16147
12-28 13:24:51.153 16147 16147 E AndroidRuntime: java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
12-28 13:24:51.153 16147 16147 E AndroidRuntime:  ViewHolder 1:DownloadHeaderHolder{386c150 position=2 id=1333211599, oldPos=-1, pLpos:-1 not recyclable(1)} 
12-28 13:24:51.153 16147 16147 E AndroidRuntime:  View Holder 2:DownloadHeaderHolder{cc13f64 position=0 id=1333211599, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{af0a5cd VFED..... ......ID 0,0-1080,2298 #7f09024b app:id/recycler}, adapter:eu.kanade.tachiyomi.ui.download.DownloadAdapter@4893e82, layout:androidx.recyclerview.widget.LinearLayoutManager@a076993, context:eu.kanade.tachiyomi.ui.main.MainActivity@9c21ebc
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:62)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:23)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$1.run(RecyclerView.java:6)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:809)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7861)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
12-28 13:24:51.153 16147 16147 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
App version: 0.12.3-4045 (standard, 42accebec, 72, 2021-12-25T21:07Z)
Android version: 11 (SDK 30)
Android build ID: RKQ1.200826.002 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: excalibur
Device model: Redmi Note 9 Pro Max
Device product name: excalibur_in

### Tachiyomi version

 0.12.3-4045 

### Android version

Android 11

### Device

Redmi note 9 pro max

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
Also I think in the dowoads somehow there were two instances of one of the sources.

**Comment by THElegend5** [comment]
Yeah I checked and somehow two instances of the same source are being created and when you try to reorder these sources the downloads get duplicated.
I don't know if it's just showing duplicates or are downloading twice as both the original and duplicate download at the same time.

**Comment by arkon** [comment]
Should be fixed in newer preview builds.

**Comment by THElegend5** [comment]
@arkon in builds after r4067?

**Comment by arkon** [comment]
Should include r4067, but let me know if it still happens.

**Comment by THElegend5** [comment]
> Should include r4067, but let me know if it still happens.

Doesn't seem to crash anymore but duplication of downloads is still happening.
